pipeline:
  build:
    image: fpfis/php56
    commands: 
      - php --version
      - composer install --ansi
      - mysqladmin -h 127.0.0.1 create platform
      - ./bin/phing build-platform-dev -Dcomposer.bin=$(which composer)
      - ./bin/phing install-platform -Dcomposer.bin=$(which composer) -Ddrupal.db.user=root -Ddrupal.db.password="" -Ddrupal.db.name=platform
      # uncached version
      - curl http://127.0.0.1:80
      # varnished version
      - curl http://127.0.0.1:6081 
services:

  web:
    image: fpfis/php56
    environment:
      - DOCROOT=/drone/src/github.com/ec-europa/platform-dev/build
  mysql:
    image: fpfis/mysql56
  redis:
    image: fpfis/redis
  varnish:
    image: fpfis/nexteuropa-varnish5
  selenium:
    image: selenium/standalone-chrome
