pipeline:
  build:
    image: fpfis/php56
    commands: 
      - php --version
      - netstat -lnp
      - mysql --version
      - mysqladmin create database1
services:
  mysql:
    image: fpfis/mysql56
  redis:
    image: fpfis/redis
  varnish:
    image: fpfis/nexteuropa-varnish5
