workspace:
  base: /test
  path: platform

services:
  # centos 6 + httpd + php${FPFIS_PHP_VERSION}
  web:
    image: fpfis/php56-dev
    environment:
      - DOCUMENT_ROOT=/test/platform/build
  # centos 6 + mysql community
  mysql:
    image: fpfis/mysql56

pipeline:

  # Step name "prepare"
  prepare-php:
    group: prepare
    # Use php${FPFIS_PHP_VERSION} image
    image: fpfis/php56
    # Run the following commands
    commands:
      - php --version
      - composer install --ansi

  # Check code standards :
  qa:
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    commands: 
      - ./bin/phpcs

  unit-test:
    group: test
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    commands:
      - ./bin/phpunit -c tests/phpunit.xml

  package:
    image: fpfis/php${FPFIS_PHP_VERSION}-dev
    when:
      environment:
        PLATFORM_PROFILE: standard
      event: tag
    commands:
      - ./bin/phing build-multisite-dist -Dcomposer.bin=$(which composer)
      - tar cz --strip-components=1 build > ../platform-dev-${DRONE_TAG}.tar.gz
