pipeline:
  build:
    image: fpfis/php56
    commands: 
      - php --version
      - netstat -lnp
      - mysql --version
      - mysqladmin -h 127.0.0.1 create database1
services:
  web:
    image: fpfis/php56

  mysql:
    image: fpfis/mysql56
  redis:
    image: fpfis/redis
  varnish:
    image: fpfis/nexteuropa-varnish5
