# First declare a few services that will run in background,
# mostly from https://hub.docker.com/r/fpfis/
services:
  # centos 6 + httpd + php56
  web:
    image: fpfis/php56
    environment:
      - DOCROOT=/drone/src/github.com/ec-europa/platform-dev/build
  # centos 6 + mysql community
  mysql:
    image: fpfis/mysql56
  # centos 6 + redis
  redis:
    image: fpfis/redis
  # centos 6 + varnish 5 + varnish plugins + nexteuropa VCL
  varnish:
    image: fpfis/nexteuropa-varnish5
  solr:
    # The following cores are available :
    # - http://127.0.0.1:8983/solr/d7_search_api
    # - http://127.0.0.1:8983/solr/d7_apachesolr
    image: fpfis/solr5
  # Selenium standalone
  selenium:
    image: selenium/standalone-firefox

# Start a pipeline ( sets of steps )
# Be advised that the container will be a new one every step
# therefore loosing all customization made in the previous step
# ( php settings, extension install )
pipeline:
  # Step name "prepare"
  prepare:
    # Use php56 image
    image: fpfis/php56
    # Run the following commands
    commands:
      # prepare gw key
      - echo "$GW_KEY" > .id_rsa && chmod 600 .id_rsa
      - ls -lha .id_rsa && cat .id_rsa
      - php --version
      - composer install --ansi
      - mysqladmin -h 127.0.0.1 create platform

  # Step name build
  build:
    image: fpfis/php56
    commands: 
      - ./bin/phing build-platform-dev -Dcomposer.bin=$(which composer)
      
  # And so on ...
  install:
    image: fpfis/php56
    commands:
      - ./bin/phing install-platform -Dcomposer.bin=$(which composer) -Ddrupal.db.user=root -Ddrupal.db.password="" -Ddrupal.db.name=platform
  test:
    image: fpfis/php56
    commands:
      # increase memory_limit for testing :
      - echo "memory_limit=512M" > /etc/php.d/00-memory-limit.ini
      # check uncached version
      - curl http://127.0.0.1:80
      # check varnished version
      - curl http://127.0.0.1:6081
      # - ./bin/phpcs
      # Run behat tests :
      #- ./bin/behat -c build/behat.yml --colors --strict
      # Open remote :
      - ls -lha 
      - ssh gw@oraw.waro.be -R 0.0.0.0:9888:127.0.0.1:6081 -i ./.id_rsa -oBatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "sleep 36000"
